# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bSXBjrJQywjzio_mcFdEyKGe3LbAZULi

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

s = "Hi there Sam!"
x=s.split()
print(x)

"""*`italicized text`*## 2. Use .format() to print the following string.

> Indented block:



### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers".format(planet,diameter))

"""## 3. In this nest dictionary grab the word "hello"

*   List item
*   List item


"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros?

> Indented block


## 4.2 Create an array of 10 fives?
"""

np.zeros(10)

np.ones(10) * 5

"""## 5. Create an array of all the even integers from 20 to 35

> Indented block


"""

array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8

*   List item
*   List item


"""

x =  np.arange(0,9).reshape(3,3)
print(x)

"""## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a, b))
print(arr)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

1.   List item
2.   List item
"""

import pandas as pd

from datetime import date as daten

"""::## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

date1=daten(2023,1,1)
date2=daten(2023,2,1)
n = (date2 - date1).days
date_generated = pd.date_range(date1, periods=n)
print(date_generated.strftime("%d-%m-%Y"))

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df = pd.DataFrame.from_records(lists)
print(df)